# Generated by Django 4.2.7 on 2025-04-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
