# Generated by Django 4.2.7 on 2025-04-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_task_completion_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='worked_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
